spring.application.name=DATN

spring.profiles.active=dev

# ===== JPA common =====
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# File upload config
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

