spring.application.name=DATN

spring.profiles.active=dev

# ===== JPA common =====
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Config multipart upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB