spring.application.name=DATN

app.qr-payment.expire-minutes=15
spring.profiles.active=dev

# ===== JPA common =====
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# File upload config
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

vnpay.pay-url=${VNP_PAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
vnpay.tmn-code=${VNP_TMN_CODE:50CQRUTK}
vnpay.hash-secret=${VNP_HASH_SECRET:7V88248X23T0M51V234479K0G98T16X2}
vnpay.api-url=${VNP_API_URL:https://sandbox.vnpayment.vn/merchant_webapi/api/transaction}
vnpay.return-url=/vnpay-return

app.base-url=https://disposal-oriented-indices-upload.trycloudflare.com